inherit_from: .rubocop_todo.yml

require:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'Schema.rb'
    - 'spec/support/database_cleaner.rb'
    - 'bin/bundle'

  SuggestExtensions: false


RSpec/InstanceVariable:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: true
  Max: 10

Layout/MultilineMethodCallIndentation:
  Enabled: false
